### ISSUE TITLE
Analytics and tracking

### ISSUE THREAD

**Issue by ymdahi** [LibreTexts/readerview#9]
todo:

- track
  - [ ] enter reader view button clicks
  - [ ] download button clicks
  - [ ] homework button clicks
  - [ ] tools button clicks

- display
  - [ ] number of downloads
